# Deployment Template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  # 2 Pods should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: maan731/loginapp2424
        ports:
        - containerPort: 80
---
# Service Template
apiVersion: v1
kind: Service
metadata:
  name: login-svc
spec:
  type: LoadBalancer
  selector:
    app: login
  ports:
    - port: 80
      